### ISSUE TITLE
Feature: User can search for an artwork. #1

### ISSUE THREAD

**Issue by annuhpark** [annuhpark/ajax--project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can search for an artwork.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users can search for a specific artwork that meets the search criteria.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![](https://user-images.githubusercontent.com/69396309/156274489-6bf943b7-d60f-44c7-805e-2ae6d47c7d0e.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

 - [x] Add a div[data-view="search-form"] to the HTML.
 - [x] Ensure that the form looks nice on both mobile-sized and desktop-sized screens.
 - [x] Make all both dropdown list and search input of the search required.
 - [x] Listen for 'submit' event on the search form.
 - [x] Verify that artwork is saved to local storage along with the rest of the data model on page reload.
 - [x] Make sure clicking 'search' leads to another page with ONE artwork that matches that search result.
 - [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
 - [x] Test all functionality again in a private browsing session.
 - [x] Fix all errors.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
