### ISSUE TITLE
Feature: User can see details of an artwork. #2

### ISSUE THREAD

**Issue by annuhpark** [annuhpark/ajax--project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can see details of an artwork.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

After an artwork is returned that fits the user's search criteria, the user can see specific details about that artwork.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="227" alt="Screen Shot 2022-04-18 at 7 53 21 PM" src="https://user-images.githubusercontent.com/69396309/163910878-8116b452-a84e-4bec-bba0-458e614cdc44.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
- [x] Make sure details of each artwork is showing with each search.
- [x] Make sure that the search results are removed after the user navigates to the main page. 

Clean Up
- [x]  Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x]  Remove all console logs.
- [x]  Remove all commented out code.
- [x]  Remove all CSS properties that have no effect.
- [x]  Check all code for proper formatting and indentation.
- [x]  Confirm that there are no errors in the console while using the application.
- [x]  Confirm that all previous functionality still works without errors.
- [x]  Confirm that the user interface looks natural on both mobile and desktop screens.
- [x]  Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
