### ISSUE TITLE
Feature: User can save an artwork to their favorites list. #3

### ISSUE THREAD

**Issue by annuhpark** [annuhpark/ajax--project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can save an artwork to their favorites list.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can save a particular artwork into their "favorites" archive.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="724" alt="Screen Shot 2022-04-19 at 10 55 17 AM" src="https://user-images.githubusercontent.com/69396309/164065963-c6e66a62-147c-4269-8546-ba8206d17772.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a `div[data-view="favorites"]` to the HTML.
- [x] Ensure that the form looks nice on both mobile-sized and desktop-sized screens.
- [x] Have the heart button directly take the user to the favorites page and the 'liked' entry must be there. 
- [x] Put the values of the liked artwork into a new object.
- [x] Add the `nextEntryId` to the object.
- [x] Increment the `nextEntryId` on the data model.
- [x] Prepend the new object to the entries in the data model.
- [x] Reset the image preview's `src' attribute.
- [x] Reset the form inputs.
- [x] Verify that new entries are saved to local storage along with the rest of the data model on page reload.
- [x] Verify that each new entry receives an incrementing `entryId`.
- [x] Have the folder icon button at top left take the user to the favorites page.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
