### ISSUE TITLE
Feature: User can view their favorites list. #4

### ISSUE THREAD

**Issue by annuhpark** [annuhpark/ajax--project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view their favorites list.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="452" alt="Screen Shot 2022-04-19 at 6 49 27 PM" src="https://user-images.githubusercontent.com/69396309/164130624-91aa9441-d45f-4626-a463-e5737f390343.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
- [x] Make sure favorites list stays the same after refreshing.
- [x] Make sure folders icon goes to favorites page.
- [x] Click on the image of each favorites entry to get the details of selected artwork. 
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
