### ISSUE TITLE
Feature: User can remove an artwork from their favorites list. #5

### ISSUE THREAD

**Issue by annuhpark** [annuhpark/ajax--project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can remove an artwork from their favorites list.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can take one of the artwork entries from their favorites list and remove it from the list.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="735" alt="Screen Shot 2022-04-20 at 3 17 16 PM" src="https://user-images.githubusercontent.com/69396309/164334181-4dfdf385-771b-4d2c-9c7f-b30040736df7.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
- [x] Add a click target (use unlink icon from font awesome) for deleting an entry to the entry form that only appears if the user is editing an entry.
- [x] Show a confirmation modal when the user clicks the Delete Entry click target.
- [x] Hide the modal if the user clicks Cancel.
- [x] Remove the entry from the data model and the entry's DOM tree from the page if the user clicks Delete.
- [x] Show the Favorites list if the user clicks Delete.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
